accounts/urls.py
from django.urls import path
from accounts import views

urlpatterns = [
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("signup/", views.signup_view, name="signup"),
]

expenses/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect


def redirect_to_receipts(request):
    return redirect("home")


urlpatterns = [
    path("admin/", admin.site.urls),
    path("receipts/", include("receipts.urls")),
    path("", redirect_to_receipts, name="redirect_to_receipts"),
    path("accounts/", include("accounts.urls")),
]

receipts/urls.py
from django.urls import path
from .views import (
    receipt_list,
    create_receipt,
    category_list,
    account_list,
    create_account,
)


urlpatterns = [
    path("", receipt_list, name="home"),
    path("create/", create_receipt, name="create_receipt"),
    path("categories/", category_list, name="category_list"),
    path("accounts/", account_list, name="account_list"),
    path("accounts/create/", create_account, name="create_account"),
]

accounts/models.py
from django.db import models

# Create your models here.

receipts/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class ExpenseCategory(models.Model):
    name = models.CharField(max_length=50)
    owner = models.ForeignKey(
        User,
        related_name="categories",
        on_delete=models.CASCADE,
    )


class Account(models.Model):
    name = models.CharField(max_length=100)
    number = models.CharField(max_length=20)
    owner = models.ForeignKey(
        User,
        related_name="accounts",
        on_delete=models.CASCADE,
    )


class Receipt(models.Model):
    vendor = models.CharField(max_length=200)
    total = models.DecimalField(max_digits=10, decimal_places=3, null=True)
    tax = models.DecimalField(max_digits=10, decimal_places=3, null=True)
    date = models.DateTimeField()
    purchaser = models.ForeignKey(
        User, related_name="receipts", on_delete=models.CASCADE
    )
    category = models.ForeignKey(
        "ExpenseCategory", related_name="receipts", on_delete=models.CASCADE
    )
    account = models.ForeignKey(
        "Account", related_name="receipts", on_delete=models.CASCADE, null=True
    )

accounts/forms.py
from django import forms


class LoginForm(forms.Form):
    username = forms.CharField(max_length=150, label="Username")
    password = forms.CharField(
        max_length=150, label="Password", widget=forms.PasswordInput
    )


class SignUpForm(forms.Form):
    username = forms.CharField(max_length=150, label="Username")
    password = forms.CharField(
        max_length=150, widget=forms.PasswordInput, label="Password"
    )
    password_confirmation = forms.CharField(
        max_length=150,
        widget=forms.PasswordInput,
        label="Password Confirmation",
    )

receipts/forms.py
from django import forms
from .models import Receipt, Account


class ReceiptForm(forms.ModelForm):
    class Meta:
        model = Receipt
        fields = ["vendor", "total", "tax", "date", "category", "account"]


class AccountForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = ["name", "number"]

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from .forms import LoginForm
from .forms import SignUpForm


# Create your views here.


def login_view(request):
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect("home")
    else:
        form = LoginForm()
    return render(request, "accounts/login.html", {"form": form})


def logout_view(request):
    logout(request)
    return redirect("login")


def signup_view(request):
    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            password_confirmation = form.cleaned_data["password_confirmation"]

            if password == password_confirmation:
                user = User.objects.create_user(username, password=password)
                login(request, user)
                return redirect("home")
            else:
                form.add_error(
                    "password_confirmation", "The passwords do not match!"
                )
    else:
        form = SignUpForm()
    return render(request, "accounts/signup.html", {"form": form})

receipts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import Receipt, ExpenseCategory, Account
from .forms import ReceiptForm, AccountForm


@login_required
def receipt_list(request):
    receipts = Receipt.objects.filter(purchaser=request.user)
    context = {"receipt_list": receipts}
    return render(request, "receipts/receipt_list.html", context)


@login_required
def create_receipt(request):
    if request.method == "POST":
        form = ReceiptForm(request.POST)
        if form.is_valid():
            receipt = form.save(commit=False)
            receipt.purchaser = request.user
            receipt.save()
            return redirect("home")
    else:
        form = ReceiptForm()
    return render(request, "receipts/create_receipt.html", {"form": form})


@login_required
def category_list(request):
    categories = ExpenseCategory.objects.filter(owner=request.user)
    context = {"category_list": categories}
    return render(request, "receipts/category_list.html", context)


@login_required
def account_list(request):
    accounts = Account.objects.filter(owner=request.user)
    context = {"account_list": accounts}
    return render(request, "receipts/account_list.html", context)


@login_required
def create_account(request):
    if request.method == "POST":
        form = AccountForm(request.POST)
        if form.is_valid():
            account = form.save(commit=False)
            account.owner = request.user
            account.save()
            return redirect("account_list")
    else:
        form = AccountForm()
    return render(request, "receipts/create_account.html", {"form": form})

accounts/templates/accounts/login.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Login</title>
  </head>
  <body>
    <main>
      <div>
        <h1>Login</h1>
        <form method="post">
          {% csrf_token %} {{ form.as_p }}
          <button type="submit">Login</button>
        </form>
        <p>
          Don't have an account?
          <a href="{% url 'signup' %}">Register</a>
        </p>
      </div>
    </main>
  </body>
</html>

accounts/templates/accounts/signup.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Sign up</title>
  </head>
  <body>
    <main>
      <div>
        <h1>Sign up</h1>
        <form method="post">
          {% csrf_token %} {{ form.as_p }}
          <button type="submit">Signup</button>
        </form>
        <p>
          Have an account?
          <a href="{% url 'login' %}">Login</a>
        </p>
      </div>
    </main>
  </body>
</html>

receipts/templates/receipts/account_list.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Category List</title>
  </head>
  <body>
    <header>
      <nav>
        <ul>
          {% if user.is_authenticated %}
          <li><a href="{% url 'home' %}">Receipts</a></li>
          <li><a href="{% url 'create_receipt' %}">Create Receipt</a></li>
          <li><a href="{% url 'category_list' %}">Categories</a></li>
          <li><a href="{% url 'account_list' %}">Accounts</a></li>
          <li><a href="{% url 'create_account' %}">Create Account</a></li>
          <li><a href="{% url 'logout' %}">Logout</a></li>
          {% endif %}
        </ul>
      </nav>
    </header>
    <main>
      <h1>Account List</h1>
      <table>
        <thead>
          <tr>
            <th>Name</th>
            <th>Account Number</th>
          </tr>
        </thead>
        <tbody>
          {% for account in account_list %}
          <tr>
            <td>{{account.name}}</td>
            <td>{{account.number}}</td>
            <td>{{account.receipt_set.count}}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </main>
  </body>
</html>

receipts/templates/receipts/category_list.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Category List</title>
  </head>
  <body>
    <header>
      <nav>
        <ul>
          {% if user.is_authenticated %}
          <li><a href="{% url 'home' %}">Receipts</a></li>
          <li><a href="{% url 'create_receipt' %}">Create Receipt</a></li>
          <li><a href="{% url 'category_list' %}">Categories</a></li>
          <li><a href="{% url 'account_list' %}">Accounts</a></li>
          <li><a href="{% url 'create_account' %}">Create Account</a></li>
          <li><a href="{% url 'logout' %}">Logout</a></li>
          {% endif %}
        </ul>
      </nav>
    </header>
    <main>
      <h1>Expense Categories</h1>
      <table>
        <thead>
          <tr>
            <th>Name</th>
            <th>Number of receipts</th>
          </tr>
        </thead>
        <tbody>
          {% for category in category_list %}
          <tr>
            <td>{{category.name}}</td>
            <td>{{category.receipt_set.count}}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </main>
  </body>
</html>

receipts/templates/receipts/create_account.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Create Account</title>
  </head>
  <body>
    <header>
      <nav>
        <ul>
          {% if user.is_authenticated %}
          <li><a href="{% url 'home' %}">Receipts</a></li>
          <li><a href="{% url 'create_receipt' %}">Create Receipt</a></li>
          <li><a href="{% url 'category_list' %}">Categories</a></li>
          <li><a href="{% url 'account_list' %}">Accounts</a></li>
          <li><a href="{% url 'create_account' %}">Create Account</a></li>
          <li><a href="{% url 'logout' %}">Logout</a></li>
          {% endif %}
        </ul>
      </nav>
    </header>
    <main>
      <div>
        <h1>Create Account</h1>
        <form method="post">
          {% csrf_token %} {{ form.as_p }}
          <button type="submit">Create</button>
        </form>
      </div>
    </main>
  </body>
</html>

receipts/templates/receipts/create_receipt.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Create Receipt</title>
  </head>
  <body>
    <header>
      <nav>
        <ul>
          {% if user.is_authenticated %}
          <li><a href="{% url 'home' %}">Receipts</a></li>
          <li><a href="{% url 'create_receipt' %}">Create Receipt</a></li>
          <li><a href="{% url 'category_list' %}">Categories</a></li>
          <li><a href="{% url 'account_list' %}">Accounts</a></li>
          <li><a href="{% url 'create_account' %}">Create Account</a></li>
          <li><a href="{% url 'logout' %}">Logout</a></li>
          {% endif %}
        </ul>
      </nav>
    </header>
    <main>
      <div>
        <h1>Create Receipt</h1>
        <form method="post">
          {% csrf_token %} {{ form.as_p }}
          <button type="submit">Create</button>
        </form>
      </div>
    </main>
  </body>
</html>

receipts/templates/receipts/receipt_list.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>My Receipts</title>
  </head>
  <body>
    <header>
      <nav>
        <ul>
          {% if user.is_authenticated %}
          <li><a href="{% url 'home' %}">Receipts</a></li>
          <li><a href="{% url 'create_receipt' %}">Create Receipt</a></li>
          <li><a href="{% url 'category_list' %}">Categories</a></li>
          <li><a href="{% url 'account_list' %}">Accounts</a></li>
          <li><a href="{% url 'create_account' %}">Create Account</a></li>
          <li><a href="{% url 'logout' %}">Logout</a></li>
          {% endif %}
        </ul>
      </nav>
    </header>
    <main>
      <h1>My Receipts</h1>
      <table>
        <thead>
          <tr>
            <th>Vendor</th>
            <th>Total</th>
            <th>Tax</th>
            <th>Date</th>
            <th>Category</th>
            <th>Account</th>
          </tr>
        </thead>
        <tbody>
          {% for receipt in receipt_list %}
          <tr>
            <td>{{receipt.vendor}}</td>
            <td>{{receipt.total}}</td>
            <td>{{receipt.tax}}</td>
            <td>{{receipt.date|date:"m/d/y"}}</td>
            <td>{{receipt.category.name}}</td>
            <td>{{receipt.account.name}}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </main>
  </body>
</html>